carpentry: swc
title: Контроль версій за допомогою Git
created: '2014-12-04'
keywords: software, data, lesson, The Carpentries
life_cycle: stable
license: CC-BY 4.0
source: https://github.com/ukrainian-carpentries/git-novice
branch: main
contact: team@carpentries.org
episodes:
- 01-basics.md
- 02-setup.md
- 03-create.md
- 04-changes.md
- 05-history.md
- 06-ignore.md
- 07-github.md
- 08-collab.md
- 09-conflict.md
- 10-open.md
- 11-licensing.md
- 12-citation.md
- 13-hosting.md
- 14-supplemental-rstudio.md
learners: ~
instructors: ~
profiles: ~
url: https://ukrainian-carpentries.github.io/git-novice/
analytics: carpentries
lang: uk
